### PR TITLE
I had to make a zip file to get githud to insert it

### PR DESCRIPTION
**Pull request by XxsuperdeadlysniperxX**
https://linksharing.samsungcloud.com/Uggc1qa3hjmN

### CODE REVIEW

**Comment by Quezler** [comment]
i can't really accept it like this, maybe ask around for how to correctly upload?

**Comment by XxsuperdeadlysniperxX** [comment]
> i can't really accept it like this, maybe ask around for how to correctly upload?

Do you know how to correctly upload?

**Comment by XxsuperdeadlysniperxX** [comment]
Idk how you accept it im on a phond and i want to upload it but the best i can do is useing the samsung cloud

**Comment by braainsiogame** [comment]
let me help you

**Comment by braainsiogame** [comment]
#maps

**Comment by XxsuperdeadlysniperxX** [comment]
Heres the actual map submitted correctly plz do not alter the design but feel free to edit the settings i would recommend a fast build speed and lots of player health
https://github.com/XxsuperdeadlysniperxX/mindustry__nydus--map-pool/pull/1

**Comment by Blockzilla101** [comment]
added this map in #29

**Pull request closed without merging**
