### PR TITLE
More maps for nydus, and i removed unnatural zone 10, as most  players didn't like it

### PR DESCRIPTION
**Pull request by modern500**

### CODE REVIEW

**Comment by Catchears** [comment]
Charred Craters seems fine, glazed grasslands seems to be a relatively generic map, but we can test it. There are some issues with permafrost: You powered the defence with solar panels but set the solar power multiplier to 0 and maybe the build multipliers are a bit harsh, but I'm happy to add it for testing if you remove the solar panels or change the multiplier. I guess sector A9 seems fine. So, to sum it up, fix permafrost and I'll merge.

**Comment by modern500** [comment]
I intend that

**Comment by modern500** [comment]
The solar thing  is  supposed  to  show  the  player the solar  multiplier

**Comment by modern500** [comment]
ALL ON PERMAFROST  2 is intended, as you can salvage  the  builds

**Pull request merged**
