### PR TITLE
add more lead, scrap and sand

### PR DESCRIPTION
**Pull request by Catchears**
I'm doing this as a PR again because I'm not sure if you'll like how I did it. 
image

Merge if you like, comment why if you don't.

### CODE REVIEW

**Comment by Quezler** [comment]
its in the way of where i want my impact walls to be

**Comment by Quezler** [comment]
maybe have it in the area covered by the enemy ripple's range on both sides?

**Comment by Quezler** [comment]
oh and lets skip on the sand, just scrap & lead there will be fine

**Comment by Catchears** [comment]
image

**Comment by Quezler** [comment]
map got updated several times

**Comment by Catchears** [comment]
> map got updated several times

those changes were merged in

**Comment by Catchears** [comment]
see https://github.com/Quezler/mindustry__nydus--map-pool/pull/75/commits/4b89c734b9f5a037eedf6ad5c5bcc8ee2aaa2162

**Comment by USMP-lancer** [comment]
yea, sand can be skipped because scrap can become snad

**Comment by Catchears** [comment]
(this has been open for too long at this point and merging it into v6 isn't going to change much anyway)

**Pull request merged**
